# Generated by Django 5.0.4 on 2024-05-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('deliveryOptionId', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartItem', models.ManyToManyField(to='orders.cartitem')),
            ],
        ),
    ]
